# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoYoutubeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoYoutubeApp
  pod 'SDWebImage', '~> 4.0'

end

target 'Model' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Model

end

target 'Service' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Service

end
